AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  every-fact-bot-2

  Sample SAM Template for every-fact-bot-2

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
#Parameters:
#  OpenAiToken:
#    Type: 'String'
#    Default: 'xxxx'
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
#    Environment:
#      Variables:
#        OpenAiToken: !Ref OpenAiToken
#        TWITTERCONSUMERKEY: !Ref TWITTERCONSUMERKEY
#        TWITTERCONSUMERSECRET: !Ref TWITTERCONSUMERSECRET
#        TWITTERACCESSTOKENKEY: !Ref TWITTERACCESSTOKENKEY
#        TWITTERACCESSTOKENSECRET: !Ref TWITTERACCESSTOKENSECRET
    Properties:
      CodeUri: every_fact_bot/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get


Outputs:
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
