version = 0.1
[default]
[default.pipeline_bootstrap]
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::780997964150:user/aws-sam-cli-managed-dev-pipeline-reso-PipelineUser-1S8B5TG2HXNGI"

[dev]
[dev.pipeline_bootstrap]
[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::780997964150:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-CL1E7T94GLMA"
cloudformation_execution_role = "arn:aws:iam::780997964150:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-FBSL57OMP6F"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-artifactsbucket-3taattuw5vft"
image_repository = ""
region = "us-west-1"

[prod]
[prod.pipeline_bootstrap]
[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::780997964150:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-KR263H48SDUO"
cloudformation_execution_role = "arn:aws:iam::780997964150:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1JIVVRO13I656"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline-artifactsbucket-16lj21ak4o5zx"
image_repository = ""
region = "us-west-1"
